export const TAX_DOCUMENTS_MIGRATION_SQL = `
CREATE TABLE IF NOT EXISTS tax_documents (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  payment_id TEXT NULL,
  subscription_id TEXT NULL,
  document_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'DRAFT',
  folio TEXT NULL,
  external_track_id TEXT NULL,
  issuer_rut TEXT NOT NULL,
  issuer_legal_name TEXT NOT NULL,
  issuer_business_activity TEXT NOT NULL,
  issuer_address TEXT NOT NULL,
  issuer_commune TEXT NOT NULL,
  issuer_city TEXT NOT NULL,
  receiver_rut TEXT NOT NULL,
  receiver_legal_name TEXT NOT NULL,
  receiver_business_activity TEXT NULL,
  receiver_address TEXT NOT NULL,
  receiver_commune TEXT NOT NULL,
  receiver_city TEXT NOT NULL,
  receiver_dte_email TEXT NOT NULL,
  net_amount INTEGER NOT NULL DEFAULT 0,
  exempt_amount INTEGER NOT NULL DEFAULT 0,
  iva_amount INTEGER NOT NULL DEFAULT 0,
  total_amount INTEGER NOT NULL DEFAULT 0,
  iva_rate NUMERIC(6,4) NOT NULL DEFAULT 0.19,
  line_items_json TEXT NOT NULL,
  reference_json TEXT NULL,
  xml_payload TEXT NULL,
  pdf_url TEXT NULL,
  external_response TEXT NULL,
  rejection_reason TEXT NULL,
  sent_at TIMESTAMP NULL,
  accepted_at TIMESTAMP NULL,
  rejected_at TIMESTAMP NULL,
  voided_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
`;
