import type { LegalSource } from "../domain/types";

export const chileCryptoTaxSources: LegalSource[] = [
  {
    id: "cl-income-tax-general",
    domain: "RENTA",
    title: "Impuesto a la Renta aplicado a resultados patrimoniales",
    authority: "Chile",
    sourceType: "LAW",
    summary: "Marco general para evaluar si una operación genera renta, resultado o incremento patrimonial sujeto a análisis tributario.",
    appliesTo: ["venta", "enajenacion", "resultado", "ganancia", "incremento patrimonial", "crypto fiat"],
    riskNotes: ["Requiere costo de adquisición", "Requiere fecha de operación", "Requiere valorización y respaldo documental"],
    version: "1.0",
  },
  {
    id: "cl-iva-general",
    domain: "IVA",
    title: "IVA y análisis de hecho gravado",
    authority: "Chile",
    sourceType: "LAW",
    summary: "Marco para revisar si una operación corresponde a venta o servicio gravado, exento o no afecto según su naturaleza.",
    appliesTo: ["servicio", "comision", "intermediacion", "actividad habitual", "plataforma"],
    riskNotes: ["No todo movimiento patrimonial implica IVA", "Debe distinguirse activo propio, servicio, comisión e intermediación"],
    version: "1.0",
  },
  {
    id: "cl-tax-code-records",
    domain: "CODIGO_TRIBUTARIO",
    title: "Deber de respaldo, trazabilidad y prueba",
    authority: "Chile",
    sourceType: "PRINCIPLE",
    summary: "Marco general de cumplimiento, conservación de antecedentes y consistencia de información frente a revisiones.",
    appliesTo: ["documentos", "respaldo", "cartola", "csv", "origen de fondos", "trazabilidad"],
    riskNotes: ["La falta de respaldo aumenta riesgo de observación", "La trazabilidad debe conectar origen, movimiento y documento"],
    version: "1.0",
  },
  {
    id: "cl-sii-crypto-criteria",
    domain: "SII_CRITERIA",
    title: "Criterios administrativos sobre activos digitales",
    authority: "Servicio de Impuestos Internos",
    sourceType: "ADMIN_CRITERIA",
    summary: "Criterios administrativos relevantes para clasificar operaciones con activos digitales caso a caso.",
    appliesTo: ["bitcoin", "criptoactivo", "token", "stablecoin", "exchange", "wallet"],
    riskNotes: ["Debe verificarse criterio vigente", "La calificación depende del hecho económico y documentación"],
    version: "1.0",
  },
  {
    id: "cl-compliance-income-tax-return",
    domain: "COMPLIANCE",
    title: "Proceso anual de declaración de renta",
    authority: "Servicio de Impuestos Internos",
    sourceType: "PROCESS",
    summary: "Proceso anual donde personas y empresas declaran ingresos y resultados del año comercial correspondiente.",
    appliesTo: ["declaracion", "operacion renta", "formulario 22", "renta anual", "abril"],
    riskNotes: ["Debe consolidarse información antes de declarar", "Inconsistencias pueden generar observaciones"],
    version: "1.0",
  },
];
